server.port=50000
server.ssl.enabled=true
server.ssl.key-store=/opt/flashcards/ssl/keystore.p12
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=flashcards
server.ssl.client-auth=none
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2

